export const product_list = [
  {
    id: 1,
    name: "商品名称 1",
    price: "20",
    points: "20",
    image: "./temp.jpg",
    link: "",
  },
  {
    id: 2,
    name: "商品名称 2",
    price: "199",
    points: "199",
    image: "./temp.jpg",
    link: "",
  },
  {
    id: 3,
    name: "商品名称 3",
    price: "99",
    points: "99",
    image: "./temp.jpg",
    link: "",
  },
  {
    id: 4,
    name: "商品名称 4",
    price: "20",
    points: "20",
    image: "./temp.jpg",
    link: "",
  },
  {
    id: 5,
    name: "商品名称 5",
    price: "199",
    points: "199",
    image: "./temp.jpg",
    link: "",
  },
  {
    id: 6,
    name: "商品名称 6",
    price: "99",
    points: "99",
    image: "./temp.jpg",
    link: "",
  },
  {
    id: 7,
    name: "商品名称 7",
    price: "50",
    points: "50",
    image: "./temp.jpg",
    link: "",
  },
  {
    id: 8,
    name: "商品名称 8",
    price: "399",
    points: "399",
    image: "./temp.jpg",
    link: "",
  },
];
